language: gcc
gcc :
  - "4.8"

install:
  - sudo apt-get install libcppunit-dev
  - gem 'coveralls-gcov'

script:
  - gcc --version
  - cmake --version
  - cd build
  - make
  - ./run_test

after_success:
  - coveralls-gcov
